# Generated by Django 3.0.2 on 2020-02-06 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cost_per_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='mo_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='mp_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='r_d_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='to_own',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_produce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=869115116),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 23, 50, 35, 457654), verbose_name='Time Submitted'),
        ),
    ]
