# Generated by Django 3.0.2 on 2020-02-06 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=530672754),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 0, 2, 9, 620124), verbose_name='Time Submitted'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=1)),
                ('machine_purchased', models.IntegerField(default=0)),
                ('to_own', models.IntegerField(default=0)),
                ('machine_operated', models.IntegerField(default=0)),
                ('r_d_purchased', models.IntegerField(default=0)),
                ('bank_balance', models.IntegerField(default=0)),
                ('mp_cost', models.IntegerField(default=0)),
                ('mo_cost', models.IntegerField(default=0)),
                ('r_d_cost', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('unit_produce', models.IntegerField(default=0)),
                ('cost_per_turn', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Company')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('game', 'turn', 'company'), name='unique_record'),
        ),
    ]
