# Generated by Django 3.0.2 on 2020-02-15 02:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200206_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='game.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=584505891),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 21, 32, 49, 187834), verbose_name='Time Submitted'),
        ),
    ]
