# Generated by Django 3.0.2 on 2020-02-15 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200214_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=328508396),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 21, 36, 43, 839769), verbose_name='Time Submitted'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='game.Company'),
        ),
    ]
