# Generated by Django 3.0.2 on 2020-02-17 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200214_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=719225901),
        ),
        migrations.AlterField(
            model_name='company',
            name='unit_produce',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 20, 30, 12, 693226), verbose_name='Time Submitted'),
        ),
        migrations.AlterField(
            model_name='record',
            name='unit_produce',
            field=models.FloatField(default=0),
        ),
    ]
