# Generated by Django 3.0.2 on 2020-02-21 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200216_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.TextField(default='Untitled'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=701857595),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 18, 29, 22, 587322), verbose_name='Time Submitted'),
        ),
    ]
