# Generated by Django 3.0.2 on 2020-02-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200221_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=338495425),
        ),
        migrations.AlterField(
            model_name='game',
            name='counter_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Submitted'),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn_num',
            field=models.IntegerField(default=0),
        ),
    ]
